default: &default
  adapter: postgresql
  host: localhost
  username: doobee46
  password:
  template: template0
  port:    5432
  timeout: 5000
development:
  <<: *default
  database: timarche_dev
test:
  <<: *default
  database: timarche_test
production:
  <<: *default
  database: timarche_prod